### ISSUE TITLE
Impossible to mount volumes and edit portal-ext.properties

### ISSUE THREAD

**Issue by KOSSOKO** [liferay/liferay-docker#34]
Hi, I just start with the dockerized version liferay.I followed the instruction to mount a volume in order to have all config files, tomcat, deploy, etc..

> Start the container with the option -v $(pwd)/xyz123:/mnt/liferay to bridge $(pwd)/xyz123 in the host operating system to /mnt/liferay on the container.
> 
> Files in the host directory $(pwd)/xyz123/files are also available in the container directory /mnt/liferay/files and will be copied to /opt/liferay before Liferay Portal starts.

In my case, I create a docker-compose file :
```
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-55JhATTpBzThxAWp}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-me@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-NZ5cM9727Bsz5JUy}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  liferay:
    container_name: liferay_container
    image: liferay/portal:7.2.1-ga2
    volumes:
       - liferay:/mnt/liferay/
    ports:
      - "80:8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    liferay:
```
But when I go inside my folder liferay, I have nothing inside. I tried mounting my liferay host folder with /opt/liferay/ in the container without success.

Please, how could I do to mount my liferay folder in order to have folders contained in my container as if it was a standalone liferay ? Thanks in advance.

Ps : I notice that I don't have the wizard setup in the liferay 7.2 how could I activate it ? thanks in advance.
